home/urls.py
from django.urls import path
from .views import *
from join.views import joinall
from mylog.views import mylog_list
from myteam.views import myteam_notice

urlpatterns=[
    path('', home, name="home"),
    path('joinall', joinall, name="joinall" ),
    path('', home, name="home"),
    path('mylog_list',mylog_list,name="mylog_list"),
    path('myteam_notice',myteam_notice,name="myteam_notice"),
]

mylog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',mylog_list,name="mylog_list"),
    path('create/',mylog_create,name='mylog_create'),
    #path('detail/',mylog_detail,name='mylog_detail'),
    path('schedule_create/',schedule_create,name='schedule_create'),
    
    #장고 modelform을 이용한 객체 생성
    path('modelformcreate/',modelformcreate ,name='modelformcreate'),
    #각 log에 대한 detail 페이지 url은 127.0.0.1:8000/mylog_detail/(id) 가 될 것
    path('mylog_detail/<int:mylog_id>',mylog_detail,name='mylog_detail'),
    #댓글 작성
    path('create_comment/<int:mylog_id>', create_comment, name='create_comment'),
]

sportly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #for media file
from django.conf.urls.static import static #for media file



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('mylog/',include('mylog.urls')),
    path('join/',include('join.urls')),
    path('login/',include('accounts.urls')),
    path('myteam/',include('myteam.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #미디어 파일에 접근할 수 있는 url추가

mylog/models.py
from datetime import datetime
from django.db import models

# Create your models here.
class Mylog(models.Model):
    log_date = models.DateTimeField(auto_now_add = True)#자동으로 현재 날짜와 시간 추가
    log_date2=models.DateTimeField(default=datetime.now())

    #mood=models.IntegerField() #각 이모티콘이 1~5의 값을 가짐.
    MOOD_CHOICES = (
        ('😡', '😡'),
        ('😠', '😠'),
        ('😐', '😐'),
        ('🙂', '🙂'),
        ('😆', '😆')
    )
    mood= models.TextField(choices = MOOD_CHOICES, default='😐')
    learned = models.TextField() #대용량 문자열, 배운 점
    lacked=models.TextField() #부족한점
    improve=models.TextField() #개선할 점
    photo = models.ImageField(blank=True, null=True, upload_to = 'mylog_photo')#비어도 되고, 없어도 된다. 
    video = models.FileField(blank=True, null=True, upload_to = 'mylog_file') #파일 업로드 사이즈 최댓값은 기본 2.5mb, 따로 설정 가능.

    #저장이 media파일 내의 blog_photo에 된다.
    #따로 primary key를 설정해주지 않은 경우, 장고가 알아서 눈에 보이지 않는 id key( value : 1,2,3....)을 만들어
    #primary key로 사용한다.
    #id를 사용하게 될 때는 객체가 만들어진 순서에 따라 숫자가 생기고 그게 primary key가 된다.
    
    #video=models....
    #writer=...(향후 User와 연결시 작성 예정.)

    def __str__(self):
        return self.learned #제목을 learned 키의 value로

class Comment(models.Model):
    comment = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add = True)
    post = models.ForeignKey(Mylog, on_delete=models.CASCADE)#외래키 블로그 객체 참조
    #on_delete어쩌구는 참조하는 대상이 삭제될 경우 같이 삭제될 것이란 뜻.

    def __str__(self):
        return self.comment #제목을 title 키의 value로. 이 함수는 db를 변경시켜주는 것은 아니라서 migrate 안해줘도 된다.

mylog/forms.py
from xml.dom.minidom import Comment
from django import forms
from .models import Mylog,Comment

class MylogModelForm(forms.ModelForm): #괄호 안은 forms 안의 ModelForm을 상속받은 클래스라는 것을 의미
    class Meta: 
        model=Mylog #meta클래스 하에 어떤 모델을 기반으로 자동으로 입력받을 form을 만들 것인지 명시
        fields = ['log_date2','mood','learned','lacked','improve','photo','video']#어떤 입력값(필드)를 입력받을지 명시
                # list 안에 원하는 필드를 작성하면 됨.
                #모두 입력 받을거면 '__all__'이라고 우측에 쓰면 됨.
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

mylog/views.py
import django
from django.shortcuts import redirect, render, get_object_or_404
from .models import Comment, Mylog
from django.utils import timezone
from .forms import MylogModelForm,CommentForm
# Create your views here.

#mylog_create.html을 보여주는 함수
def mylog_create(request):
    return render(request,'mylog_create.html')

#mylog_list.html을 보여주는 함수
def mylog_list(request):
    #작성한 로그들을 띄우는 코드
    #posts = Mylog.objects.all() 
    posts=Mylog.objects.filter().order_by('-log_date2') #최신글 순서로 정렬
    return render(request,'mylog_list.html',{'posts':posts})

#mylog_id번째 로그를 mylog_detail.html에 보여주는 함수
def mylog_detail(request, mylog_id):
    mylog_detail = get_object_or_404(Mylog, pk=mylog_id)
    comment_form = CommentForm()
    return render(request,'mylog_detail.html', {'mylog_detail':mylog_detail, 'comment_form':comment_form})

#schedule_create.html을 보여주는 함수
def schedule_create(request):
    return render(request,'schedule_create.html')

#장고 모델 폼
def modelformcreate(request): 
    if request.method == 'POST' or request.method == 'FILES': #해당되는 urls.py에서 요청한 대상이 post 요청을 보낸 경우
        form = MylogModelForm(request.POST,request.FILES)
        if form.is_valid(): #정상적인 값이 입력된 경우
            form.save() #form에서 입력된 값 저장
        return redirect('mylog_list')
    else: #get 요청을 보낸 경우
        form = MylogModelForm() #모델폼을 그대로 찍어 보내줘라.
    return render(request, 'mylog_create.html', {'form':form})

def create_comment(request, mylog_id):
    filled_form = CommentForm(request.POST)
    if filled_form.is_valid(): 
        filled_form = filled_form.save(commit=False) #아직은 저장하지 말고 대기하라는 뜻.
        filled_form.post = get_object_or_404(Mylog, pk= mylog_id ) #게시물 id 불러옴
        filled_form.save() #이제 저장하세요.
    return redirect('mylog_detail',mylog_id)

mylog/templates/mylog_create.html
<!--my log를 작성하는 페이지-->
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/mylog_create.css">
    <title>로그 작성 일지</title>
</head>
<body>
    <p> 내 로그 작성 페이지 </p>
    <!--
    <input type ="date" id="currentDate">
    <script>
        document.getElementById('currentDate').value = new Date().toISOString().substring(0,10);;
    </script>

    <h1>오늘의 운동 만족도는 어떠셨나요?</h1>
    <ul class="feeling-list">
        <li class="emojifeeling">&#128545;</li>
        <li class="emojifeeling">&#128533;</li>
        <li class="emojifeeling">&#128528;</li>
        <li class="emojifeeling">&#128578;</li>
        <li class="emojifeeling">&#128540;</li>
    </ul>
    <script>
        var feelingnumber; //feelingnumber 라는 변수 = 0,1,2,3,4 순서대로 만족도 높아짐!!! -> mylog에서 기록 저장시 함께 저장
        document.querySelectorAll('.feeling-list')[0].addEventListener("click", function(e) {
            if(e.target.dataset.id != null) {
                feelingnumber = e.target.dataset.id;
                // console.log(feelingnumber);
                // 추가사항: 선택한 이모티콘의 사이즈가 40px로 커지도록!!
                // document.querySelectorAll(".emojifeeling")[feelingnumber].style.fontSize = "40px";
            }
        });
    </script>

    <div class="page-background">
        <form action="#" method="post">
            <div>
                <label for="learned" class="title1">배운 점</label>
                <br>
                <input type="text" name="learned" class="writing-can" id="learned" rows="4">-->
                <!--js: 글자 줄 수 만큼 칸 늘어나게 하는 기능 추가해야함!-->
            
            <!--</div>
            <div>
                <label for="lacked" class="title1">부족한 점</label>
                <br>
                <input type="text" name="lacked" class="writing-can" id="lacked" rows="4">
            </div>
            <div>
                <label for="improve" class="title1">개선할 점</label>
                <br>
                <input type="text" name="improve" class="writing-can" id="improve" rows="4">
            </div>
        </form>-->

        <!--사진/동영상 업로드-->
        <!--<h2>사진/비디오 추가</h2>
        <div class="img-upload">
            <label for="img-file"><div>+</div></label>
            <input type="file" id="img-file" accept="image/*,video/mp4, video/mkv, video/x-m4v,video/*" multiple>-->
            <!--업로드한 사진 미리보기 기능 추가해야함 !-->
        <!--</div>-->

            
        <!--업로드한 비디오 미리보기 기능-->
        <!--<video id="video-play"></video>
        <script>
            const inputFile = document.getElementById("img-file");
            const video = document.getElementById("video-play");

            inputFile.addEventListener("change", function(){
                const file = inputFile.files[0];
                const videourl = URL.createObjectURL(file);
                video.setAttribute("src", videourl);
                video.play();
            });
        </script>

        <input type="button" class="mylogcreate-button" value="등록하기">
    </div>

    <input type="button" value="등록하기">-->

    <form action=" " method="POST" enctype="multipart/form-data">
    <!--이 방식은 <form> 요소가 파일이나 이미지를 서버로 전송할 때 주로 사용함 위에 enctype-->
    {%csrf_token%}
    <!--views.py 에서 render()의 세번째 인자로 넘겨준 딕셔너리형 데이터는 html 내에서 \{\{}}에 갑싸진 채로 표현 가능하다.-->
    <table>
        {{form.as_table}}
        <!--위에 form말고 form.as_table로 쓰면 자동으로 table에 감싸진 것처럼 나온다.-->
        <!--.as_p로 쓰면 자동으로 <p>에 감싸진 것처럼 나온다.-->
        <!--.as_ul로 쓰면 자동으로 <ul>에 감싸진 것처럼 나온다.-->
    </table>
    <input type="submit" value="등록하기">
    </form>
</body>
</html>

mylog/templates/mylog_detail.html
<!--내 로그 자세히 보기. 로그 목록에서 하나 클릭시
하나의 로그를 자세히 띄움. 댓글을 작성 및 확인 가능-->
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>my log 자세히 보기</title>
    <link rel="stylesheet" href="css/mylog_detail.css">
</head>
<body>
    내 로그 자세히 보는 페이지
    <h1>날짜2</h1>
    {{mylog_detail.log_date2}}
    <h3>기분</h3>
    {{mylog_detail.mood}}
    <h3>배운 점</h3>
    {{mylog_detail.learned}}
    <h3>부족한 점</h3>
    {{mylog_detail.lacked}}
    <h3>개선할 점</h3>
    {{mylog_detail.improve}}
    <h3>사진</h3>
    {% if mylog_detail.photo %}
        <img src="{{mylog_detail.photo.url}}" alt="" height="600">
    {% endif %}
    <h3>비디오</h3>
    {% if mylog_detail.video %}
        <video src="{{mylog_detail.video.url}}"  width="1000px" height="700px"></video>   
    {% endif %}

    <hr>
    <h3>댓글</h3>
    <form method="POST" action="{% url 'create_comment' mylog_detail.id %}"> 
        {% csrf_token %}
        {{comment_form}}
        <input type ="submit">
    </form>
    <hr>
    <!--댓글 목록들-->
    {% for comment in mylog_detail.comment_set.all %}
    <p>{{comment}}</p>
    <hr>
    {% endfor %}
    
    <!--연우 작성 코드-->
    <!--<div class="up-basic-info">
        <img class="myprofileimg" src="#"> 사용자가 등록한 프로필 사진
        <h1>지연우</h1> innerHTML 텍스트 : 작성자 이름
        <h3>2022.07.24</h3> 작성 날짜: #currentdate에서 입력받은 날짜
    </div>

    <div class="mylog-content">
        <h2>배운 점</h2>
        <h4>이런것들을 배웠습니다.</h4> innerHTML 텍스트 : 사용자가 등록한 배운점
        <h2>부족한 점</h2>
        <h4>이런것들이 부족합니다.</h4> innerHTML 텍스트 : 사용자가 등록한 부족한점
        <h2>개선할 점</h2>
        <h4>이런것들을 개선해야 합니다.</h4> innerHTML 텍스트 : 사용자가 등록한 개선할점
    </div>-->


</body>
</html>

mylog/templates/mylog_list.html
<!--메뉴바에서 mylog를 누르면 가장 처음 보이는 페이지,
작성했던 로그들이 화면에 나열된다.-->

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Log 확인</title>
</head>
<body>
    <a href="{% url 'modelformcreate' %}">내 로그 작성하기</a><br>
    <a href="{% url 'schedule_create' %}">일정 등록하기</a><br>
    
    <hr>
    <!--이 아래로 로그들을 띄운다.-->
    {% for post in posts %}
        <h3>날짜 : {{post.log_date}}</h3>
        <a href="{% url 'mylog_detail' post.id %}"><h3>날짜2 : {{post.log_date2}}</h3></a> <!--클릭시 detail페이지로 이동, post.id는 추가로 필요한 정보를 넘겨주는 거다.--> 
        <h6>기분 : {{post.mood}}</h6>
        <h6>배운점 : {{post.learned}}</h6>
        <hr>
    {% endfor %}
</body>
</html>

mylog/templates/schedule_create.html
<!--달력에 일정을 등록하는 페이지-->
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>일정 등록하기</title>
    <link rel="stylesheet" href="css/schedule_create.css">
</head>
<body>
    <h2>새로운 일정 등록</h2>
    <input type="text" class="writing-schedule"></textarea>
    <br>

    <h2>날짜 선택</h2>
    <input type ="date" id="currentDate">
    <script>
        document.getElementById('currentDate').value = new Date().toISOString().substring(0,10);;
    </script>
    <br>

    <h2>일정 색상</h2>
    <input type="color" id="schedule-color" value="#524FFF">
    <!-- 색상 6가지 정도 후보 제시해서 선택할 수 있도록 기능 추가하기-->
    <br>

    <input type="button" class="mylogcreate-button" value="등록하기">
</body>
</html>